#!/bin/bash

# Reset shell colors
tput init

# Get the directory of the script
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$PROJECT_ROOT/$SOURCE"
done
PROJECT_ROOT="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# Required imports
source "${PROJECT_ROOT}/variables/manifest.sh"
source "${PROJECT_ROOT}/utils/manifest.sh"
source "${PROJECT_ROOT}/lib/manifest.sh"

# User configs file
if [[ ! -e "${PROJECT_ROOT}/config" ]]; then
  cat << EOF > "${PROJECT_ROOT}/config"
deploy_password=${deploy_password}
mysql_root_password=${mysql_root_password}
db_pass=${db_pass}
EOF
fi

# Set permissions for config file
sudo chown root:root "${PROJECT_ROOT}/config"
sudo chmod 700 "${PROJECT_ROOT}/config"
source "${PROJECT_ROOT}/config"

# Interactive CLI
inquiry_options

# Dependencies related
system_update
system_node_install
system_pm2_install
system_docker_install
system_puppeteer_dependencies
system_snapd_install
system_nginx_install

# Backend related
system_git_clone
backend_set_env
backend_redis_create
backend_node_dependencies
backend_node_build
backend_db_migrate
backend_db_seed
backend_start_pm2

# Nginx setup
sudo rm /etc/nginx/sites-enabled/default
cat << EOF | sudo tee /etc/nginx/sites-available/whaticket
server {
    listen 80;
    server_name _;
    location / {
        proxy_pass http://localhost:3000; # Assuming backend runs on port 3000
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_cache_bypass \$http_upgrade;
    }
}
EOF
sudo ln -s /etc/nginx/sites-available/whaticket /etc/nginx/sites-enabled/
sudo systemctl restart nginx

echo "WhatiTicket installed and configured. You can access it at http://your_ip_address"
